name: fluttertest
description: "A new Flutter project."
 
publish_to: 'none'
 
version: 1.0.0+1
 
environment:
  sdk: ^3.8.1
 
 
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  badges: ^3.1.2
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  http: ^1.5.0
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1  
  flutter_secure_storage: ^9.0.0  
  image_picker: ^1.0.4  
  file_picker: ^10.3.2
  flutter_staggered_grid_view: ^0.7.0
  responsive_builder: ^0.7.1
  socket_io_client: ^3.1.2
  table_calendar: ^3.0.9
  intl: ^0.19.0
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  google_sign_in: ^6.1.5
  firebase_messaging: ^16.0.1
  flutter_local_notifications: ^19.4.1
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  fl_chart: ^0.68.0
  go_router: ^14.2.0
  fluttertoast: ^8.2.4
  flutter_spinkit: ^5.2.1
  curved_navigation_bar: ^1.0.6
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  shimmer: ^3.0.0
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  get_it: ^7.6.7
  injectable: ^2.1.2
  mime: ^1.0.4
  http_parser: ^4.0.2
  excel: ^2.1.0
  pdf: ^3.10.9
  file_saver: ^0.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  logger: ^2.0.2
  share_plus: ^7.2.1
  cross_file: ^0.3.4
  dartz: ^0.10.1
  url_launcher: ^6.2.2
  permission_handler: ^11.3.0
    # Real-time video/audio (added for Live Session integration)

  livekit_client: ^2.5.0+hotfix.3
 
  # Basic dependencies only for now
  # sqflite: ^2.3.0
  # path: ^1.8.3
  # video_player: ^2.8.1
  # chewie: ^1.7.4
  # firebase_core: ^2.24.2
  # firebase_messaging: ^14.7.10
  # flutter_local_notifications: ^16.3.2
  # workmanager: ^0.5.2
  # fuzzywuzzy: ^1.1.6
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.4"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/miskills_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  windows:
    generate: true
    image_path: "assets/images/miskills_logo.png"
    icon_size: 48 # min:48, max:256, default: 48
 
flutter:
  uses-material-design: true
 
  assets:
    - assets/
    - assets/images/
    - assets/images/google_logo.png
    - assets/icons/